### ISSUE TITLE
phpcpd exclude pattern not work as expected.

### ISSUE THREAD

**Issue by LeeShan87** [EdgedesignCZ/phpqa#225] opened 2021-04-21 14:49 UTC
Recently I had to ugrade phpqa and all its tools to latest.
I have noticed when used phpcpd 6.0.3, then my exclude directory patterns were not working as expected.
Downgrading phpcd to 5.0.2 solved my problem.

This issue could be related to:
[https://github.com/sebastianbergmann/phpcpd/issues/192](https://github.com/sebastianbergmann/phpcpd/issues/192)

This might be useful, if you facing with this issue.

**Comment by zdenekdrahos** [comment] 2021-04-24 06:36
Is it a problem in phpqa? I don't see any BC in [phpcpd's changelog](https://github.com/sebastianbergmann/phpcpd/blob/master/ChangeLog.md#603---2020-12-07) that should be fixed. phpqa is using `--exclude` from [the beginning](https://github.com/EdgedesignCZ/phpqa/blame/master/tests/IgnoredPathsTest.php#L101). Please add more info _(phpcpd console command with options would be useful for experimenting)_.

**Comment by spipu** [comment] 2021-04-28 16:31
before, phpcpd accepts patterns, now it only accept absolute and relative path.

**Comment by spipu** [comment] 2021-04-29 07:18
it seems coming from this : https://github.com/sebastianbergmann/php-file-iterator/blob/master/src/Factory.php
now --exclude must be a real absolute, relative, or pattern path. 
"Test" will not work if it is in a sub folder. It must be for example "src/*/test" for example

**Comment by zdenekdrahos** [comment] 2021-04-30 09:50
If I understand it correctly. It's about what you pass in [`--ignoredDirs` or `--ignoredFiles`](https://github.com/EdgedesignCZ/phpqa#analyze). Please reopen, if there is a bug in phpqa.

![image](https://user-images.githubusercontent.com/7994022/116678742-fb8fbb00-a9a9-11eb-96f4-d3a78ce9b6eb.png)

**Closed by zdenekdrahos** 2021-04-30 09:50 UTC

**Comment by spipu** [comment] 2021-04-30 10:37
for me it is not a bug on PhpQa, but a new way to deal with phpcpd.

now, in the Phpqa configuration, the exclude parameters must be real pattern path, from the execution folder.
